export const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID ;
export const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET ;
export const NEXT_PUBLIC_RAZORPAY_KEY_ID = process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID ;
export const NEXT_PUBLIC_RAZORPAY_KEY_SECRET = process.env.NEXT_PUBLIC_RAZORPAY_KEY_SECRET;
export const NEXT_PUBLIC_STRAPI_API_URL = process.env.NEXT_PUBLIC_STRAPI_API_URL;
export const STRAPI_API_URL = process.env.STRAPI_API_URL;